# Generated by Django 5.2.6 on 2025-10-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_csvimportlog_alter_occasion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_customization',
            field=models.BooleanField(default=False, help_text='Allow customers to customize this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_flavor_selection',
            field=models.BooleanField(default=False, help_text='Allow flavor selection'),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_message_customization',
            field=models.BooleanField(default=False, help_text='Allow custom message'),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_name_customization',
            field=models.BooleanField(default=False, help_text='Allow name on product (e.g., cake)'),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_note',
            field=models.TextField(blank=True, help_text='Instructions for customization'),
        ),
    ]
