# Generated by Django 5.2.6 on 2025-10-06 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_advanced_menu_models'),
        ('users', '0003_pincode_seller_sellerlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Quantity in pending orders')),
                ('reorder_level', models.PositiveIntegerField(default=5, help_text='Minimum stock before reorder')),
                ('seller_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use product base price', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_inventory', to='products.product')),
                ('seller_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='users.sellerlocation')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_inventory', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Seller Inventory',
                'verbose_name_plural': 'Seller Inventories',
                'ordering': ['seller_location', 'product'],
                'unique_together': {('seller_location', 'product', 'variant')},
            },
        ),
    ]
