# Generated by Django 5.2.6 on 2025-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sellerinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='addons/')),
            ],
            options={
                'verbose_name': 'Product Add-On',
                'verbose_name_plural': 'Product Add-Ons',
                'ordering': ['name'],
            },
        ),
    ]
