# Generated by Django 5.2.6 on 2025-10-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days for delivery'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_personalized',
            field=models.BooleanField(default=False, help_text='Product can be personalized'),
        ),
    ]
