# Generated by Django 5.2.6 on 2025-10-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_data',
            field=models.JSONField(blank=True, help_text='Additional customization data', null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_date',
            field=models.DateField(blank=True, help_text='Custom date (e.g., delivery date)', null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_flavor',
            field=models.CharField(blank=True, help_text='Flavor preference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_message',
            field=models.TextField(blank=True, help_text='Custom message/text on product', null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Name to be written (e.g., on cake)', max_length=100, null=True),
        ),
    ]
