# Generated by Django 5.2.6 on 2025-10-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_unique_together_cartitem_custom_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='abandonment_email_sent',
            field=models.BooleanField(default=False, help_text='Whether abandonment email has been sent'),
        ),
        migrations.AddField(
            model_name='cart',
            name='abandonment_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When abandonment email was sent', null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, help_text='Last time cart was updated'),
        ),
    ]
