# Generated by Django 5.2.6 on 2025-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_abandonment_email_sent_and_more'),
        ('products', '0007_product_delivery_days_product_is_personalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='products.productaddon'),
        ),
    ]
