# Generated by Django 5.2.6 on 2025-10-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional mobile-optimized image', null=True, upload_to='banners/mobile/')),
                ('link_url', models.URLField(blank=True, help_text='URL to navigate when banner is clicked')),
                ('button_text', models.CharField(blank=True, help_text='Text for call-to-action button', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number = higher priority')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
