# Generated by Django 5.2.6 on 2025-10-10 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bannerimage'),
        ('products', '0007_product_delivery_days_product_is_personalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldwideDeliveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_note', models.CharField(blank=True, help_text='Special delivery instructions', max_length=200)),
                ('estimated_delivery_days', models.PositiveIntegerField(default=7, help_text='Estimated delivery days internationally')),
                ('international_shipping_charge', models.DecimalField(decimal_places=2, default=0, help_text='Additional shipping charge for international delivery', max_digits=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured worldwide delivery section')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('countries', models.ManyToManyField(blank=True, related_name='deliverable_products', to='core.country')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldwide_delivery', to='products.product')),
            ],
            options={
                'verbose_name': 'Worldwide Delivery Product',
                'verbose_name_plural': 'Worldwide Delivery Products',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
